# Generated by Django 4.2.16 on 2025-03-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrecord',
            name='detection_type',
            field=models.CharField(choices=[('image', '图片检测'), ('video', '视频检测')], default='image', max_length=20, verbose_name='检测类型'),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='media_path',
            field=models.CharField(default='', max_length=255, verbose_name='媒体路径'),
        ),
    ]
