# Generated by Django 4.2.16 on 2025-03-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_detectionrecord_detection_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='probability',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='结果概率'),
        ),
    ]
