# Generated by Django 4.2.16 on 2025-03-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_detectionrecord_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrecord',
            name='report_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='检测报告路径'),
        ),
    ]
