# Generated by Django 4.2.16 on 2025-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrecord',
            name='detection_type',
            field=models.CharField(default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='media_path',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
