# Generated by Django 4.2.16 on 2025-03-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_detectionrecord_detection_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectionRecord',
        ),
    ]
